### PR TITLE
Format with scalafmt

### PR DESCRIPTION
**Pull request by Shalsh23**

### CODE REVIEW

**Comment by balhoff** [comment]
Is there a setting to line up `%` characters in the `build.sbt` dependencies list?

**Comment by hlapp** [comment]
@balhoff perhaps the people you know have widescreen monitors. I don't, and a lot of the people I know remain committed old school to 80 chars per line. I view/review _a lot_ of code on the command line, and honestly the common arrogance of people with widescreen monitors drives me nuts.

**Comment by balhoff** [comment]
@hlapp I’m only referring to my 13 inch laptop screen 😂

**Comment by balhoff** [comment]
Right now my line-breaking practice is a bit arbitrary. I would like to use scalafmt to make it more deterministic. But something greater than 80 characters...

**Pull request closed without merging**
