### PR TITLE
Remove conflicting settings in scalafmt config

### PR DESCRIPTION
**Pull request by Shalsh23**
Also, removed some other unnecessary config.

### CODE REVIEW

**Comment by Shalsh23** [comment]
@balhoff Is this alignment a bit too much? If so, I can reduce it; change value of `align.preset` from `most` to `more`, or even `some`.

**Comment by balhoff** [comment]
Sorry, I caused a bunch of conflicts for you. Can you reformat from the current master?

**Comment by Shalsh23** [comment]
> Sorry, I caused a bunch of conflicts for you. Can you reformat from the current master?

Yup, I was just waiting for your approval for the revised configs. Let me do a clean pull and reformat it.

**Comment by Shalsh23** [comment]
Closing this PR - doing a clean pull on a new branch.

**Pull request closed without merging**
